// Date: 4/8/2014 9:35:42 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package DuBCraft21.mob;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class testMob extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer foot1;
    ModelRenderer foot2;
    ModelRenderer foot3;
    ModelRenderer foot4;
  
  public testMob()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 2);
      head.addBox(-7F, -10F, 0F, 14, 10, 14);
      head.setRotationPoint(0F, 0F, -5F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 0, 26);
      body.addBox(-5F, 0F, 0F, 10, 20, 10);
      body.setRotationPoint(0F, 0F, -3F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      foot1 = new ModelRenderer(this, 0, 56);
      foot1.addBox(-4F, 0F, 0F, 4, 4, 4);
      foot1.setRotationPoint(5F, 20F, -3F);
      foot1.setTextureSize(64, 64);
      foot1.mirror = true;
      setRotation(foot1, 0F, 0F, 0F);
      foot2 = new ModelRenderer(this, 0, 56);
      foot2.addBox(0F, 0F, 0F, 4, 4, 4);
      foot2.setRotationPoint(-5F, 20F, -3F);
      foot2.setTextureSize(64, 64);
      foot2.mirror = true;
      setRotation(foot2, 0F, 0F, 0F);
      foot3 = new ModelRenderer(this, 0, 56);
      foot3.addBox(-4F, 0F, -4F, 4, 4, 4);
      foot3.setRotationPoint(5F, 20F, 7F);
      foot3.setTextureSize(64, 64);
      foot3.mirror = true;
      setRotation(foot3, 0F, 0F, 0F);
      foot4 = new ModelRenderer(this, 0, 56);
      foot4.addBox(0F, 0F, -4F, 4, 4, 4);
      foot4.setRotationPoint(-5F, 20F, 7F);
      foot4.setTextureSize(64, 64);
      foot4.mirror = true;
      setRotation(foot4, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7) {
    setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    head.render(par7);
    body.render(par7);
    foot1.render(par7);
    foot2.render(par7);
    foot3.render(par7);
    foot4.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, float par7, Entity par7Entity)
  {
    
	  //head Movement
	  this.head.rotateAngleY = par4 / (180F / (float)Math.PI);
	  this.head.rotateAngleX = par5 / (170F / (float)Math.PI);
	  //head movement end
	  
	  // foot1 movement
	  this.foot1.rotateAngleX = MathHelper.cos((float) (par1 * 0.6662 + (float)Math.PI)) * 1.4F * par2;
	  this.foot1.rotateAngleY = 0.0F;
	  
	  //foot2 movement
	  this.foot2.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
	  
	  //foot3 movement
	  this.foot3.rotateAngleX = MathHelper.cos((float) (par1 * 0.6662 + (float)Math.PI)) * 1.4F * par2;
	  this.foot3.rotateAngleY = 0.0F;
	  
	  //foot4 movement
	  this.foot4.rotateAngleX = MathHelper.cos(par1 * 0.6662F) * 1.4F * par2;
  }

}
